### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by oschwald** [jaimeamesti/HttpServerMock#1]
Right now this repo seems to consist only of a README without any code. Are you planning on releasing the code?

**Comment by jaimeamesti** [comment]
Of course, but it will be in a near future. I have to clean up the code first. If you are interested in the libraries, you can find them here: https://www.nuget.org/packages/HttpServerMock/

**Comment by jaimeamesti** [comment]
Hi again,

I've just uploaded the code, sorry for the delay :)
